name: DR-GPCRact
channels:
  - schrodinger
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - cudatoolkit=11.8.0
  - pytorch
  - torchvision
  - torchaudio
  - torch-geometric
  - rdkit
  - biopython
  - h5py
  - numpy
  - scipy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - tensorflow
  - fair-esm
  - e3nn
  - openbabel
  - apbs
  - autodock-vina
  - pip:
      - shap==0.41.0
      - plotly==5.18.0
      - tqdm==4.64.1